apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eva-db
  namespace: eva
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: eva
  labels:
    type: local
    app: postgres
spec:
  storageClassName: eva-db
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
    type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: eva
  labels:
    app: postgres
spec:
  storageClassName: eva-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
