apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: eva
  labels:
    app: postgres
data:
  POSTGRES_DB: evadb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: servicemode
  POSTGRES_INITDB_ARGS: "--encoding=UTF8"
  POSTGRES_HOST_AUTH_METHOD: md5
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_CONF_EXTRA: |
    listen_addresses='*'
    max_connections=100
    shared_buffers=256MB
    work_mem=16MB
