apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: eva
  labels:
    app: postgres
spec:
  # type: NodePort
  # type: ClusterIP(default)
  ports:
   - port: 5432
  selector:
   app: postgres
