apiVersion: batch/v1
kind: Job
metadata:
  # generateName: eva-init-
  name: eva-init
  namespace: eva
spec:
  template:
    spec:
      initContainers:
      - name: tmp-volume-init
        image: docker-registry.evateam.ru/evateam:devel_psb_astra-v00.00.00.0009-devel_psb_astra-temporary
        command: ["/usr/bin/rsync", "-a", "/mnt/tmp/", "/mnt/tmp-init/"]

        volumeMounts:
          - mountPath: /mnt/tmp-init
            name: eva-tmp

        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 0

      containers:
      - name: eva-init
        image: docker-registry.evateam.ru/evateam:devel_psb_astra-v00.00.00.0009-devel_psb_astra-temporary
        # imagePullPolicy: IfNotPresent
        args: ["/opt/bin/eva_init.sh", "k8s-init"]
        
        env:
        - name: EVA_DEPLOY_TYPE
          value: k8s

        envFrom:
        - secretRef:
            name: eva-init-secret
            optional: true

        volumeMounts:
          - mountPath: /mnt/configs
            name: eva-config
            readOnly: true
          - mountPath: /mnt/tls
            name: eva-tls
            readOnly: true
          - mountPath: /mnt/postgres-tls
            name: postgres-tls
            readOnly: true
          - mountPath: /mnt/redis-tls
            name: redis-tls
            readOnly: true
          - mountPath: /mnt/shared
            name: eva-shared
          - mountPath: /mnt/tmp
            name: eva-tmp

        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 0

        # terminationGracePeriodSeconds: 120
        # readinessGates: []

      volumes:
      - name: eva-config
        configMap:
          name: eva-config

      - name: eva-tls
        secret:
          secretName: eva-tls
          optional: true

      - name: postgres-tls
        secret:
          secretName: postgres-tls
          optional: true

      - name: redis-tls
        secret:
          secretName: redis-tls
          optional: true

      - name: eva-shared
        persistentVolumeClaim:
          claimName: eva-shared-pvc

      - name: eva-tmp
        emptyDir: {}
      
      restartPolicy: Never
      # activeDeadlineSeconds: 300
  backoffLimit: 1
