# https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
# https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
# kubectl create secret tls eva-tls --cert=path/to/cert/file --key=path/to/key/file
#
apiVersion: v1
kind: Secret
metadata:
  name: eva-init-secret
  namespace: eva
stringData:
  # Параметры подключения к Redis и PostgreSQL
  EVA_CONFIG__REDIS_PASSWORD: "PASS"
  EVA_CONFIG__DB_URL: "postgresql+psycopg2://postgres:servicemode@postgres:5432/evadb"
---
# Секрет для TLS (опционально)
apiVersion: v1
kind: Secret
metadata:
  name: eva-tls
  namespace: eva
type: kubernetes.io/tls
data:
  # Оставляем пустым для автогенерации самоподписного сертификата
  tls.crt: ""
  tls.key: ""
