apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eva-shared
  namespace: eva
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: eva-shared-pv
  namespace: eva
  labels:
    type: local
    app: eva
spec:
  storageClassName: eva-shared
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/eva/shared"
    type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eva-shared-pvc
  namespace: eva
  labels:
    app: eva
spec:
  storageClassName: eva-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi