apiVersion: v1
kind: Service
metadata:
  name: eva
  namespace: eva
  labels:
    app: eva
spec:
  # type: NodePort
  # type: ClusterIP(default)
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: eva

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eva
  namespace: eva
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
  - hosts: ["eva.example.ru"]
    secretName: eva-tls
  rules:
  - host: eva.example.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eva
            port:
              number: 443
