version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: eva_postgres
    environment:
      POSTGRES_DB: evadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: servicemode
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c listen_addresses='*'
      -c max_connections=100
      -c shared_buffers=256MB
      -c work_mem=16MB
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: eva_redis
    command: redis-server --requirepass "PASS"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=PASS
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    sysctls:
      - net.core.somaxconn=511
    restart: unless-stopped

volumes:
  postgres_data:
    name: eva_postgres_data
  redis_data:
    name: eva_redis_data

networks:
  default:
    name: eva_network