apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: eva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command: 
            - "sh"
            - "-c"
            - |
              redis-server /usr/local/etc/redis/redis.conf --requirepass "${PASS}"
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: PASS
      volumes:
        - name: config
          configMap:
            name: redis-config
